package com.radhika.dpi.report;

import java.io.FileOutputStream;

import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import com.radhika.dpi.parser.HTTPParser;
import com.radhika.dpi.statistics.HostStatisticsManager;
import com.radhika.dpi.security.PortScanDetector;
import com.radhika.dpi.flow.Flow;
import com.radhika.dpi.flow.FlowManager;
import java.util.Map;
import com.lowagie.text.Table;
import com.lowagie.text.Document;
import com.lowagie.text.Paragraph;
import com.lowagie.text.Font;
import com.lowagie.text.FontFactory;
import com.lowagie.text.pdf.PdfWriter;

public class PDFReportGenerator {

        public static void generateReport() {

                try {

                        // Step 1: Create PDF document object
                        Document document = new Document();

                        // Step 2: Connect document with PDF file
                        PdfWriter.getInstance(
                                        document,
                                        new FileOutputStream("DPI_Report.pdf"));

                        // Step 3: Open document for writing
                        document.open();

                        // Step 4: Create title font
                        Font titleFont = FontFactory.getFont(
                                        FontFactory.HELVETICA_BOLD,
                                        18);

                        // Step 5: Add title
                        Paragraph title = new Paragraph(
                                        "Deep Packet Inspection Report",
                                        titleFont);

                        document.add(title);

                        // Step 6: Add description and timestamp

                        document.add(
                                        new Paragraph(
                                                        "Generated by Java DPI Engine"));

                        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd-MM-yyyy HH:mm:ss");

                        String timestamp = LocalDateTime.now().format(formatter);

                        document.add(
                                        new Paragraph(
                                                        "Report Generated: " + timestamp));

                        // Add spacing
                        document.add(new Paragraph("\n"));

                        // Report Summary heading
                        Font headingFont = FontFactory.getFont(
                                        FontFactory.HELVETICA_BOLD,
                                        14);

                        // Font for table data
                        Font tableFont = FontFactory.getFont(
                                        FontFactory.HELVETICA,
                                        9);
                        document.add(
                                        new Paragraph(
                                                        "Report Summary",
                                                        headingFont));

                        // Calculate flow statistics
                        int tcpFlows = 0;
                        int udpFlows = 0;

                        long totalPackets = 0;
                        long totalBytes = 0;

                        for (Flow flow : FlowManager.getFlows().values()) {

                                if ("TCP".equals(flow.protocol))
                                        tcpFlows++;

                                if ("UDP".equals(flow.protocol))
                                        udpFlows++;

                                totalPackets += flow.packetCount;
                                totalBytes += flow.totalBytes;
                        }

                        // Add summary to PDF
                        document.add(
                                        new Paragraph(
                                                        "Total Flows : " + FlowManager.getFlows().size() + "\n" +
                                                                        "TCP Flows : " + tcpFlows + "\n" +
                                                                        "UDP Flows : " + udpFlows + "\n" +
                                                                        "Total Packets : " + totalPackets + "\n" +
                                                                        "Total Bytes : " + totalBytes));
                        // Add spacing
                        document.add(new Paragraph("\n"));

                        // Threat Summary heading
                        document.add(
                                        new Paragraph(
                                                        "Threat Summary",
                                                        headingFont));

                        // Threat details
                        document.add(
                                        new Paragraph(
                                                        "HTTP Requests : " + HTTPParser.getHttpRequests() + "\n" +
                                                                        "Port Scan Alerts : "
                                                                        + PortScanDetector.getTotalAlerts() + "\n" +
                                                                        "Suspicious Hosts : "
                                                                        + PortScanDetector.getSuspiciousHosts() + "\n" +
                                                                        "Top Talker : "
                                                                        + HostStatisticsManager.getTopTalker()));

                        // Add spacing
                        document.add(new Paragraph("\n"));

                        // Flow Details heading
                        document.add(
                                        new Paragraph(
                                                        "Flow Details",
                                                        headingFont));

                        // Create table with 6 columns
                        Table table = new Table(6);

                        table.setWidth(100);
                        table.setWidths(new float[] {
                                        2.5f, // Source IP
                                        2.5f, // Destination IP
                                        1.2f, // Protocol
                                        1.5f, // Service
                                        1f, // Packets
                                        1.3f // Bytes
                        });

                        table.addCell("Source IP");
                        table.addCell("Destination IP");
                        table.addCell("Protocol");
                        table.addCell("Service");
                        table.addCell("Packets");
                        table.addCell("Bytes");

                        // Fetch actual flows
                        Map<String, Flow> flows = FlowManager.getFlows();

                        for (Flow flow : flows.values()) {

                                table.addCell(new Paragraph(flow.sourceIP, tableFont));
                                table.addCell(new Paragraph(flow.destinationIP, tableFont));
                                table.addCell(new Paragraph(flow.protocol, tableFont));
                                table.addCell(new Paragraph(
                                                flow.service != null ? flow.service : "Unknown",
                                                tableFont));
                                table.addCell(new Paragraph(
                                                String.valueOf(flow.packetCount),
                                                tableFont));
                                table.addCell(new Paragraph(
                                                String.valueOf(flow.totalBytes),
                                                tableFont));
                        }

                        // Add table to PDF
                        document.add(table);
                        // Step 7: Close document
                        document.close();

                        System.out.println(
                                        "PDF Report Generated Successfully!");

                } catch (Exception e) {

                        e.printStackTrace();

                }

        }

        /*private static long getTotalBytes() {

                long totalBytes = 0;

                for (Flow flow : FlowManager.getFlows().values()) {
                        totalBytes += flow.totalBytes;
                }

                return totalBytes;
        }*/
}